<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('federal_dists', function (Blueprint $table) {
            $table->id();
            $table->integer('parentid');
            $table->string('name');
        });

        $federalDist = array(
            array('id' => '1','parentid' => '0','name' => 'Россия'),
            array('id' => '2','parentid' => '1','name' => 'Центральный'),
            array('id' => '3','parentid' => '1','name' => 'Северо-Западный'),
            array('id' => '4','parentid' => '1','name' => 'Южный'),
            array('id' => '5','parentid' => '1','name' => 'Северо-Кавказский'),
            array('id' => '6','parentid' => '1','name' => 'Приволжский'),
            array('id' => '7','parentid' => '1','name' => 'Уральский'),
            array('id' => '8','parentid' => '1','name' => 'Сибирский'),
            array('id' => '9','parentid' => '1','name' => 'Дальневосточный'),
            array('id' => '10','parentid' => '3','name' => 'Санкт-Петербург и Ленинградская область'),
            array('id' => '11','parentid' => '3','name' => 'Коми'),
            array('id' => '12','parentid' => '3','name' => 'Архангельская область'),
            array('id' => '13','parentid' => '3','name' => 'Вологодская область'),
            array('id' => '14','parentid' => '3','name' => 'Калининградская область'),
            array('id' => '15','parentid' => '10','name' => 'Шлиссельбург'),
            array('id' => '16','parentid' => '3','name' => 'Мурманская область'),
            array('id' => '17','parentid' => '3','name' => 'Новгородская область'),
            array('id' => '18','parentid' => '3','name' => 'Псковская область'),
            array('id' => '19','parentid' => '3','name' => 'Карелия'),
            array('id' => '20','parentid' => '3','name' => 'Ненецкий АО'),
            array('id' => '21','parentid' => '1','name' => 'Вся Россия'),
            array('id' => '22','parentid' => '21','name' => 'Вся Россия'),
            array('id' => '23','parentid' => '2','name' => 'Белгородская область'),
            array('id' => '24','parentid' => '2','name' => 'Брянская область'),
            array('id' => '25','parentid' => '2','name' => 'Владимирская область'),
            array('id' => '26','parentid' => '2','name' => 'Воронежская область'),
            array('id' => '27','parentid' => '2','name' => 'Ивановская область'),
            array('id' => '28','parentid' => '2','name' => 'Калужская область'),
            array('id' => '29','parentid' => '2','name' => 'Костромская область'),
            array('id' => '30','parentid' => '2','name' => 'Курская область'),
            array('id' => '31','parentid' => '2','name' => 'Липецкая область'),
            array('id' => '32','parentid' => '2','name' => 'Москва и Московская область'),
            array('id' => '33','parentid' => '2','name' => 'Московская область'),
            array('id' => '34','parentid' => '2','name' => 'Орловская область'),
            array('id' => '35','parentid' => '2','name' => 'Рязанская область'),
            array('id' => '36','parentid' => '2','name' => 'Смоленская область'),
            array('id' => '37','parentid' => '2','name' => 'Тамбовская область'),
            array('id' => '38','parentid' => '2','name' => 'Тверская область'),
            array('id' => '39','parentid' => '2','name' => 'Тульская область'),
            array('id' => '40','parentid' => '2','name' => 'Ярославская область'),
            array('id' => '41','parentid' => '6','name' => 'Башкортостан'),
            array('id' => '42','parentid' => '6','name' => 'Марий Эл'),
            array('id' => '43','parentid' => '6','name' => 'Мордовия'),
            array('id' => '44','parentid' => '6','name' => 'Татарстан'),
            array('id' => '45','parentid' => '6','name' => 'Удмуртия'),
            array('id' => '46','parentid' => '6','name' => 'Чувашия'),
            array('id' => '47','parentid' => '6','name' => 'Пензенская область'),
            array('id' => '48','parentid' => '6','name' => 'Самарская область'),
            array('id' => '49','parentid' => '6','name' => 'Саратовская область'),
            array('id' => '50','parentid' => '6','name' => 'Ульяновская область'),
            array('id' => '51','parentid' => '10','name' => 'Бокситогорск'),
            array('id' => '52','parentid' => '10','name' => 'Волосово'),
            array('id' => '53','parentid' => '10','name' => 'Волхов'),
            array('id' => '54','parentid' => '10','name' => 'Всеволожск'),
            array('id' => '55','parentid' => '10','name' => 'Выборг'),
            array('id' => '56','parentid' => '10','name' => 'Гатчина'),
            array('id' => '57','parentid' => '10','name' => 'Ивангород'),
            array('id' => '58','parentid' => '10','name' => 'Кингисепп'),
            array('id' => '59','parentid' => '10','name' => 'Кириши'),
            array('id' => '60','parentid' => '10','name' => 'Кировск'),
            array('id' => '61','parentid' => '10','name' => 'Коммунар'),
            array('id' => '62','parentid' => '10','name' => 'ЛодейноеПоле'),
            array('id' => '63','parentid' => '10','name' => 'Луга'),
            array('id' => '64','parentid' => '10','name' => 'Никольское'),
            array('id' => '65','parentid' => '10','name' => 'НоваяЛадога'),
            array('id' => '66','parentid' => '10','name' => 'Отрадное'),
            array('id' => '67','parentid' => '10','name' => 'Пикалёво'),
            array('id' => '68','parentid' => '10','name' => 'Подпорожье'),
            array('id' => '69','parentid' => '10','name' => 'Приозерск'),
            array('id' => '70','parentid' => '10','name' => 'Светогорск'),
            array('id' => '71','parentid' => '10','name' => 'Сельцо'),
            array('id' => '72','parentid' => '10','name' => 'Сертолово'),
            array('id' => '73','parentid' => '10','name' => 'Сланцы'),
            array('id' => '74','parentid' => '10','name' => 'СосновыйБор'),
            array('id' => '75','parentid' => '10','name' => 'Сясьстрой'),
            array('id' => '76','parentid' => '10','name' => 'Тихвин'),
            array('id' => '77','parentid' => '10','name' => 'Тосно'),
            array('id' => '78','parentid' => '10','name' => 'Санкт-Петербург'),
            array('id' => '79','parentid' => '10','name' => 'Зеленогорск'),
            array('id' => '80','parentid' => '10','name' => 'Колпино'),
            array('id' => '81','parentid' => '10','name' => 'Красное Село'),
            array('id' => '82','parentid' => '10','name' => 'Кронштадт'),
            array('id' => '83','parentid' => '10','name' => 'Ломоносов'),
            array('id' => '84','parentid' => '11','name' => 'Воркута'),
            array('id' => '85','parentid' => '11','name' => 'Вуктыл'),
            array('id' => '86','parentid' => '11','name' => 'Емва'),
            array('id' => '87','parentid' => '11','name' => 'Инта'),
            array('id' => '88','parentid' => '11','name' => 'Микунь'),
            array('id' => '89','parentid' => '11','name' => 'Печора'),
            array('id' => '90','parentid' => '11','name' => 'Сосногорск'),
            array('id' => '91','parentid' => '11','name' => 'Сыктывкар'),
            array('id' => '92','parentid' => '11','name' => 'Усинск'),
            array('id' => '93','parentid' => '12','name' => 'Архангельск'),
            array('id' => '94','parentid' => '12','name' => 'Вельск'),
            array('id' => '95','parentid' => '12','name' => 'Каргополь'),
            array('id' => '96','parentid' => '12','name' => 'Коряжма'),
            array('id' => '97','parentid' => '12','name' => 'Котлас'),
            array('id' => '98','parentid' => '12','name' => 'Мирный'),
            array('id' => '99','parentid' => '12','name' => 'Новодвинск'),
            array('id' => '100','parentid' => '12','name' => 'Няндома'),
            array('id' => '101','parentid' => '12','name' => 'Онега'),
            array('id' => '102','parentid' => '12','name' => 'Северодвинск'),
            array('id' => '103','parentid' => '12','name' => 'Сольвычегодск'),
            array('id' => '104','parentid' => '13','name' => 'Бабаево'),
            array('id' => '105','parentid' => '13','name' => 'ВеликийУстюг'),
            array('id' => '106','parentid' => '13','name' => 'Вологда'),
            array('id' => '107','parentid' => '13','name' => 'Вытегра'),
            array('id' => '108','parentid' => '13','name' => 'Грязовец'),
            array('id' => '109','parentid' => '13','name' => 'Кириллов'),
            array('id' => '110','parentid' => '13','name' => 'Никольск'),
            array('id' => '111','parentid' => '13','name' => 'Сокол'),
            array('id' => '112','parentid' => '13','name' => 'Тотьма'),
            array('id' => '113','parentid' => '13','name' => 'Устюжна'),
            array('id' => '114','parentid' => '13','name' => 'Харовск'),
            array('id' => '115','parentid' => '14','name' => 'Балтийск'),
            array('id' => '116','parentid' => '14','name' => 'Гвардейск'),
            array('id' => '117','parentid' => '14','name' => 'Гурьевск'),
            array('id' => '118','parentid' => '14','name' => 'Гусев'),
            array('id' => '119','parentid' => '14','name' => 'Зеленоградск'),
            array('id' => '120','parentid' => '14','name' => 'Калининград'),
            array('id' => '121','parentid' => '14','name' => 'Мамоново'),
            array('id' => '122','parentid' => '14','name' => 'Неман'),
            array('id' => '123','parentid' => '14','name' => 'Полесск'),
            array('id' => '124','parentid' => '14','name' => 'Светлогорск'),
            array('id' => '125','parentid' => '14','name' => 'Светлый'),
            array('id' => '126','parentid' => '14','name' => 'Славск'),
            array('id' => '127','parentid' => '14','name' => 'Советск'),
            array('id' => '128','parentid' => '16','name' => 'Апатиты'),
            array('id' => '129','parentid' => '16','name' => 'Гаджиево'),
            array('id' => '130','parentid' => '16','name' => 'Кандалакша'),
            array('id' => '131','parentid' => '16','name' => 'Кировск'),
            array('id' => '132','parentid' => '16','name' => 'Ковдор'),
            array('id' => '133','parentid' => '16','name' => 'Кола'),
            array('id' => '134','parentid' => '16','name' => 'Мончегорск'),
            array('id' => '135','parentid' => '16','name' => 'Мурманск'),
            array('id' => '136','parentid' => '16','name' => 'Оленегорск'),
            array('id' => '137','parentid' => '16','name' => 'ПолярныеЗори'),
            array('id' => '138','parentid' => '16','name' => 'Полярный'),
            array('id' => '139','parentid' => '16','name' => 'Североморск'),
            array('id' => '140','parentid' => '17','name' => 'Боровичи'),
            array('id' => '141','parentid' => '17','name' => 'Валдай'),
            array('id' => '142','parentid' => '17','name' => 'ВеликийНовгород'),
            array('id' => '143','parentid' => '17','name' => 'МалаяВишера'),
            array('id' => '144','parentid' => '17','name' => 'Окуловка'),
            array('id' => '145','parentid' => '17','name' => 'Пестово'),
            array('id' => '146','parentid' => '17','name' => 'Сольцы'),
            array('id' => '147','parentid' => '17','name' => 'СтараяРусса'),
            array('id' => '148','parentid' => '18','name' => 'ВеликиеЛуки'),
            array('id' => '149','parentid' => '18','name' => 'Невель'),
            array('id' => '150','parentid' => '18','name' => 'Новосокольники'),
            array('id' => '151','parentid' => '18','name' => 'Опочка'),
            array('id' => '152','parentid' => '18','name' => 'Остров'),
            array('id' => '153','parentid' => '18','name' => 'Печоры'),
            array('id' => '154','parentid' => '18','name' => 'Порхов'),
            array('id' => '155','parentid' => '18','name' => 'Псков'),
            array('id' => '156','parentid' => '18','name' => 'Пустошка'),
            array('id' => '157','parentid' => '18','name' => 'Пыталово'),
            array('id' => '158','parentid' => '19','name' => 'Беломорск'),
            array('id' => '159','parentid' => '19','name' => 'Кемь'),
            array('id' => '160','parentid' => '19','name' => 'Кондопога'),
            array('id' => '161','parentid' => '19','name' => 'Костомукша'),
            array('id' => '162','parentid' => '19','name' => 'Медвежьегорск'),
            array('id' => '163','parentid' => '19','name' => 'Олонец'),
            array('id' => '164','parentid' => '19','name' => 'Петрозаводск'),
            array('id' => '165','parentid' => '19','name' => 'Питкяранта'),
            array('id' => '166','parentid' => '19','name' => 'Пудож'),
            array('id' => '167','parentid' => '19','name' => 'Сегежа'),
            array('id' => '168','parentid' => '19','name' => 'Сортавала'),
            array('id' => '169','parentid' => '23','name' => 'Алексеевка'),
            array('id' => '170','parentid' => '23','name' => 'Белгород'),
            array('id' => '171','parentid' => '23','name' => 'Валуйки'),
            array('id' => '172','parentid' => '23','name' => 'Губкин'),
            array('id' => '173','parentid' => '23','name' => 'НовыйОскол'),
            array('id' => '174','parentid' => '23','name' => 'СтарыйОскол'),
            array('id' => '175','parentid' => '23','name' => 'Строитель'),
            array('id' => '176','parentid' => '24','name' => 'Брянск'),
            array('id' => '177','parentid' => '24','name' => 'Дятьково'),
            array('id' => '178','parentid' => '24','name' => 'Жуковка'),
            array('id' => '179','parentid' => '24','name' => 'Карачев'),
            array('id' => '180','parentid' => '24','name' => 'Клинцы'),
            array('id' => '181','parentid' => '24','name' => 'Новозыбков'),
            array('id' => '182','parentid' => '24','name' => 'Почеп'),
            array('id' => '183','parentid' => '24','name' => 'Севск'),
            array('id' => '184','parentid' => '24','name' => 'Стародуб'),
            array('id' => '185','parentid' => '24','name' => 'Сураж'),
            array('id' => '186','parentid' => '24','name' => 'Трубчевск'),
            array('id' => '187','parentid' => '25','name' => 'Александров'),
            array('id' => '188','parentid' => '25','name' => 'Владимир'),
            array('id' => '189','parentid' => '25','name' => 'Вязники'),
            array('id' => '190','parentid' => '25','name' => 'Гороховец'),
            array('id' => '191','parentid' => '25','name' => 'Гусь-Хрустальный'),
            array('id' => '192','parentid' => '25','name' => 'Камешково'),
            array('id' => '193','parentid' => '25','name' => 'Карабаново'),
            array('id' => '194','parentid' => '25','name' => 'Киржач'),
            array('id' => '195','parentid' => '25','name' => 'Ковров'),
            array('id' => '196','parentid' => '25','name' => 'Кольчугино'),
            array('id' => '197','parentid' => '25','name' => 'Лакинск'),
            array('id' => '198','parentid' => '25','name' => 'Меленки'),
            array('id' => '199','parentid' => '25','name' => 'Муром'),
            array('id' => '200','parentid' => '25','name' => 'Петушки'),
            array('id' => '201','parentid' => '25','name' => 'Покров'),
            array('id' => '202','parentid' => '25','name' => 'Радужный'),
            array('id' => '203','parentid' => '25','name' => 'Собинка'),
            array('id' => '204','parentid' => '25','name' => 'Струнино'),
            array('id' => '205','parentid' => '25','name' => 'Судогда'),
            array('id' => '206','parentid' => '25','name' => 'Суздаль'),
            array('id' => '207','parentid' => '26','name' => 'Бобров'),
            array('id' => '208','parentid' => '26','name' => 'Богучар'),
            array('id' => '209','parentid' => '26','name' => 'Борисоглебск'),
            array('id' => '210','parentid' => '26','name' => 'Бутурлиновка'),
            array('id' => '211','parentid' => '26','name' => 'Воронеж'),
            array('id' => '212','parentid' => '26','name' => 'Калач'),
            array('id' => '213','parentid' => '26','name' => 'Лиски'),
            array('id' => '214','parentid' => '26','name' => 'Нововоронеж'),
            array('id' => '215','parentid' => '26','name' => 'Новохопёрск'),
            array('id' => '216','parentid' => '26','name' => 'Острогожск'),
            array('id' => '217','parentid' => '26','name' => 'Павловск'),
            array('id' => '218','parentid' => '26','name' => 'Поворино'),
            array('id' => '219','parentid' => '26','name' => 'Россошь'),
            array('id' => '220','parentid' => '26','name' => 'Семилуки'),
            array('id' => '221','parentid' => '27','name' => 'Вичуга'),
            array('id' => '222','parentid' => '27','name' => 'Заволжск'),
            array('id' => '223','parentid' => '27','name' => 'Иваново'),
            array('id' => '224','parentid' => '27','name' => 'Кинешма'),
            array('id' => '225','parentid' => '27','name' => 'Кохма'),
            array('id' => '226','parentid' => '27','name' => 'Наволоки'),
            array('id' => '227','parentid' => '27','name' => 'Приволжск'),
            array('id' => '228','parentid' => '27','name' => 'Пучеж'),
            array('id' => '229','parentid' => '27','name' => 'Родники'),
            array('id' => '230','parentid' => '27','name' => 'Тейково'),
            array('id' => '231','parentid' => '27','name' => 'Фурманов'),
            array('id' => '232','parentid' => '27','name' => 'Шуя'),
            array('id' => '233','parentid' => '27','name' => 'Южа'),
            array('id' => '234','parentid' => '28','name' => 'Балабаново'),
            array('id' => '235','parentid' => '28','name' => 'Белоусово'),
            array('id' => '236','parentid' => '28','name' => 'Боровск'),
            array('id' => '237','parentid' => '28','name' => 'Ермолино'),
            array('id' => '238','parentid' => '28','name' => 'Жуков'),
            array('id' => '239','parentid' => '28','name' => 'Калуга'),
            array('id' => '240','parentid' => '28','name' => 'Киров'),
            array('id' => '241','parentid' => '28','name' => 'Козельск'),
            array('id' => '242','parentid' => '28','name' => 'Кондрово'),
            array('id' => '243','parentid' => '28','name' => 'Кремёнки'),
            array('id' => '244','parentid' => '28','name' => 'Людиново'),
            array('id' => '245','parentid' => '28','name' => 'Малоярославец'),
            array('id' => '246','parentid' => '28','name' => 'Медынь'),
            array('id' => '247','parentid' => '28','name' => 'Мосальск'),
            array('id' => '248','parentid' => '28','name' => 'Обнинск'),
            array('id' => '249','parentid' => '28','name' => 'Сосенский'),
            array('id' => '250','parentid' => '28','name' => 'Сухиничи'),
            array('id' => '251','parentid' => '28','name' => 'Таруса'),
            array('id' => '252','parentid' => '29','name' => 'Буй'),
            array('id' => '253','parentid' => '29','name' => 'Волгореченск'),
            array('id' => '254','parentid' => '29','name' => 'Галич'),
            array('id' => '255','parentid' => '29','name' => 'Кострома'),
            array('id' => '256','parentid' => '29','name' => 'Мантурово'),
            array('id' => '257','parentid' => '29','name' => 'Нерехта'),
            array('id' => '258','parentid' => '30','name' => 'Дмитриев'),
            array('id' => '259','parentid' => '30','name' => 'Железногорск'),
            array('id' => '260','parentid' => '30','name' => 'Курск'),
            array('id' => '261','parentid' => '30','name' => 'Курчатов'),
            array('id' => '262','parentid' => '30','name' => 'Льгов'),
            array('id' => '263','parentid' => '30','name' => 'Обоянь'),
            array('id' => '264','parentid' => '30','name' => 'Рыльск'),
            array('id' => '265','parentid' => '30','name' => 'Суджа'),
            array('id' => '266','parentid' => '30','name' => 'Фатеж'),
            array('id' => '267','parentid' => '31','name' => 'Грязи'),
            array('id' => '268','parentid' => '31','name' => 'Данков'),
            array('id' => '269','parentid' => '31','name' => 'Елец'),
            array('id' => '270','parentid' => '31','name' => 'Задонск'),
            array('id' => '271','parentid' => '31','name' => 'Лебедянь'),
            array('id' => '272','parentid' => '31','name' => 'Липецк'),
            array('id' => '273','parentid' => '31','name' => 'Усмань'),
            array('id' => '274','parentid' => '32','name' => 'Яхрома'),
            array('id' => '275','parentid' => '32','name' => 'Апрелевка'),
            array('id' => '276','parentid' => '32','name' => 'Балашиха'),
            array('id' => '277','parentid' => '32','name' => 'Бронницы'),
            array('id' => '278','parentid' => '32','name' => 'Видное'),
            array('id' => '279','parentid' => '32','name' => 'Волоколамск'),
            array('id' => '280','parentid' => '32','name' => 'Воскресенск'),
            array('id' => '281','parentid' => '32','name' => 'Голицыно'),
            array('id' => '282','parentid' => '32','name' => 'Дедовск'),
            array('id' => '283','parentid' => '32','name' => 'Дзержинский'),
            array('id' => '284','parentid' => '32','name' => 'Дмитров'),
            array('id' => '285','parentid' => '32','name' => 'Долгопрудный'),
            array('id' => '286','parentid' => '32','name' => 'Домодедово'),
            array('id' => '287','parentid' => '32','name' => 'Дубна'),
            array('id' => '288','parentid' => '32','name' => 'Егорьевск'),
            array('id' => '289','parentid' => '32','name' => 'Железнодорожный'),
            array('id' => '290','parentid' => '32','name' => 'Жуковский'),
            array('id' => '291','parentid' => '32','name' => 'Зарайск'),
            array('id' => '292','parentid' => '32','name' => 'Звенигород'),
            array('id' => '293','parentid' => '32','name' => 'Ивантеевка'),
            array('id' => '294','parentid' => '32','name' => 'Истра'),
            array('id' => '295','parentid' => '32','name' => 'Кашира'),
            array('id' => '296','parentid' => '32','name' => 'Клин'),
            array('id' => '297','parentid' => '32','name' => 'Коломна'),
            array('id' => '298','parentid' => '32','name' => 'Королёв'),
            array('id' => '299','parentid' => '32','name' => 'Котельники'),
            array('id' => '300','parentid' => '32','name' => 'Красноармейск'),
            array('id' => '301','parentid' => '32','name' => 'Красногорск'),
            array('id' => '302','parentid' => '32','name' => 'Кубинка'),
            array('id' => '303','parentid' => '32','name' => 'Куровское'),
            array('id' => '304','parentid' => '32','name' => 'Ликино-Дулёво'),
            array('id' => '305','parentid' => '32','name' => 'Лобня'),
            array('id' => '306','parentid' => '32','name' => 'Лосино-Петровский'),
            array('id' => '307','parentid' => '32','name' => 'Луховицы'),
            array('id' => '308','parentid' => '32','name' => 'Лыткарино'),
            array('id' => '309','parentid' => '32','name' => 'Люберцы'),
            array('id' => '310','parentid' => '32','name' => 'Можайск'),
            array('id' => '311','parentid' => '32','name' => 'Московский'),
            array('id' => '312','parentid' => '32','name' => 'Мытищи'),
            array('id' => '313','parentid' => '32','name' => 'Наро-Фоминск'),
            array('id' => '314','parentid' => '32','name' => 'Ногинск'),
            array('id' => '315','parentid' => '32','name' => 'Одинцово'),
            array('id' => '316','parentid' => '32','name' => 'Озёры'),
            array('id' => '317','parentid' => '32','name' => 'Орехово-Зуево'),
            array('id' => '318','parentid' => '32','name' => 'ПавловскийПосад'),
            array('id' => '319','parentid' => '32','name' => 'Пересвет'),
            array('id' => '320','parentid' => '32','name' => 'Подольск'),
            array('id' => '321','parentid' => '32','name' => 'Протвино'),
            array('id' => '322','parentid' => '32','name' => 'Пушкино'),
            array('id' => '323','parentid' => '32','name' => 'Пущино'),
            array('id' => '324','parentid' => '32','name' => 'Раменское'),
            array('id' => '325','parentid' => '32','name' => 'Реутов'),
            array('id' => '326','parentid' => '32','name' => 'Рошаль'),
            array('id' => '327','parentid' => '32','name' => 'Руза'),
            array('id' => '328','parentid' => '32','name' => 'СергиевПосад'),
            array('id' => '329','parentid' => '32','name' => 'Серпухов'),
            array('id' => '330','parentid' => '32','name' => 'Солнечногорск'),
            array('id' => '331','parentid' => '32','name' => 'СтараяКупавна'),
            array('id' => '332','parentid' => '32','name' => 'Ступино'),
            array('id' => '333','parentid' => '32','name' => 'Талдом'),
            array('id' => '334','parentid' => '32','name' => 'Фрязино'),
            array('id' => '335','parentid' => '32','name' => 'Химки'),
            array('id' => '336','parentid' => '32','name' => 'Хотьково'),
            array('id' => '337','parentid' => '32','name' => 'Черноголовка'),
            array('id' => '338','parentid' => '32','name' => 'Чехов'),
            array('id' => '339','parentid' => '32','name' => 'Шатура'),
            array('id' => '340','parentid' => '32','name' => 'Щёлково'),
            array('id' => '341','parentid' => '32','name' => 'Электрогорск'),
            array('id' => '342','parentid' => '32','name' => 'Электросталь'),
            array('id' => '343','parentid' => '32','name' => 'Электроугли'),
            array('id' => '344','parentid' => '34','name' => 'Болхов'),
            array('id' => '345','parentid' => '34','name' => 'Ливны'),
            array('id' => '346','parentid' => '34','name' => 'Мценск'),
            array('id' => '347','parentid' => '35','name' => 'Касимов'),
            array('id' => '348','parentid' => '35','name' => 'Кораблино'),
            array('id' => '349','parentid' => '35','name' => 'Михайлов'),
            array('id' => '350','parentid' => '35','name' => 'Новомичуринск'),
            array('id' => '351','parentid' => '35','name' => 'Рыбное'),
            array('id' => '352','parentid' => '35','name' => 'Ряжск'),
            array('id' => '353','parentid' => '35','name' => 'Рязань'),
            array('id' => '354','parentid' => '35','name' => 'Сасово'),
            array('id' => '355','parentid' => '35','name' => 'Скопин'),
            array('id' => '356','parentid' => '35','name' => 'Спас-Клепики'),
            array('id' => '357','parentid' => '35','name' => 'Спасск-Рязанский'),
            array('id' => '358','parentid' => '36','name' => 'Велиж'),
            array('id' => '359','parentid' => '36','name' => 'Вязьма'),
            array('id' => '360','parentid' => '36','name' => 'Гагарин'),
            array('id' => '361','parentid' => '36','name' => 'Десногорск'),
            array('id' => '362','parentid' => '36','name' => 'Дорогобуж'),
            array('id' => '363','parentid' => '36','name' => 'Починок'),
            array('id' => '364','parentid' => '36','name' => 'Рославль'),
            array('id' => '365','parentid' => '36','name' => 'Сафоново'),
            array('id' => '366','parentid' => '36','name' => 'Смоленск'),
            array('id' => '367','parentid' => '37','name' => 'Жердевка'),
            array('id' => '368','parentid' => '37','name' => 'Кирсанов'),
            array('id' => '369','parentid' => '37','name' => 'Котовск'),
            array('id' => '370','parentid' => '37','name' => 'Мичуринск'),
            array('id' => '371','parentid' => '37','name' => 'Моршанск'),
            array('id' => '372','parentid' => '37','name' => 'Рассказово'),
            array('id' => '373','parentid' => '37','name' => 'Тамбов'),
            array('id' => '374','parentid' => '38','name' => 'Бежецк'),
            array('id' => '375','parentid' => '38','name' => 'Бологое'),
            array('id' => '376','parentid' => '38','name' => 'ВышнийВолочёк'),
            array('id' => '377','parentid' => '38','name' => 'Зубцов'),
            array('id' => '378','parentid' => '38','name' => 'Калязин'),
            array('id' => '379','parentid' => '38','name' => 'Кашин'),
            array('id' => '380','parentid' => '38','name' => 'Кимры'),
            array('id' => '381','parentid' => '38','name' => 'Конаково'),
            array('id' => '382','parentid' => '38','name' => 'Лихославль'),
            array('id' => '383','parentid' => '38','name' => 'Нелидово'),
            array('id' => '384','parentid' => '38','name' => 'Осташков'),
            array('id' => '385','parentid' => '38','name' => 'Ржев'),
            array('id' => '386','parentid' => '38','name' => 'Старица'),
            array('id' => '387','parentid' => '38','name' => 'Тверь'),
            array('id' => '388','parentid' => '38','name' => 'Торжок'),
            array('id' => '389','parentid' => '38','name' => 'Торопец'),
            array('id' => '390','parentid' => '39','name' => 'Алексин'),
            array('id' => '391','parentid' => '39','name' => 'Богородицк'),
            array('id' => '392','parentid' => '39','name' => 'Болохово'),
            array('id' => '393','parentid' => '39','name' => 'Венёв'),
            array('id' => '394','parentid' => '39','name' => 'Донской'),
            array('id' => '395','parentid' => '39','name' => 'Ефремов'),
            array('id' => '396','parentid' => '39','name' => 'Кимовск'),
            array('id' => '397','parentid' => '39','name' => 'Киреевск'),
            array('id' => '398','parentid' => '39','name' => 'Липки'),
            array('id' => '399','parentid' => '39','name' => 'Новомосковск'),
            array('id' => '400','parentid' => '39','name' => 'Плавск'),
            array('id' => '401','parentid' => '39','name' => 'Суворов'),
            array('id' => '402','parentid' => '39','name' => 'Тула'),
            array('id' => '403','parentid' => '39','name' => 'Узловая'),
            array('id' => '404','parentid' => '39','name' => 'Щёкино'),
            array('id' => '405','parentid' => '40','name' => 'Мышкин'),
            array('id' => '406','parentid' => '40','name' => 'Переславль-Залесский'),
            array('id' => '407','parentid' => '40','name' => 'Пошехонье'),
            array('id' => '408','parentid' => '40','name' => 'Ростов'),
            array('id' => '409','parentid' => '40','name' => 'Рыбинск'),
            array('id' => '410','parentid' => '40','name' => 'Тутаев'),
            array('id' => '411','parentid' => '40','name' => 'Углич'),
            array('id' => '412','parentid' => '40','name' => 'Ярославль'),
            array('id' => '413','parentid' => '41','name' => 'Агидель'),
            array('id' => '414','parentid' => '41','name' => 'Баймак'),
            array('id' => '415','parentid' => '41','name' => 'Белебей'),
            array('id' => '416','parentid' => '41','name' => 'Белорецк'),
            array('id' => '417','parentid' => '41','name' => 'Бирск'),
            array('id' => '418','parentid' => '41','name' => 'Благовещенск'),
            array('id' => '419','parentid' => '41','name' => 'Давлеканово'),
            array('id' => '420','parentid' => '41','name' => 'Дюртюли'),
            array('id' => '421','parentid' => '41','name' => 'Ишимбай'),
            array('id' => '422','parentid' => '41','name' => 'Кумертау'),
            array('id' => '423','parentid' => '41','name' => 'Межгорье'),
            array('id' => '424','parentid' => '41','name' => 'Мелеуз'),
            array('id' => '425','parentid' => '41','name' => 'Нефтекамск'),
            array('id' => '426','parentid' => '41','name' => 'Октябрьский'),
            array('id' => '427','parentid' => '41','name' => 'Салават'),
            array('id' => '428','parentid' => '41','name' => 'Сибай'),
            array('id' => '429','parentid' => '41','name' => 'Стерлитамак'),
            array('id' => '430','parentid' => '41','name' => 'Туймазы'),
            array('id' => '431','parentid' => '41','name' => 'Уфа'),
            array('id' => '432','parentid' => '41','name' => 'Учалы'),
            array('id' => '433','parentid' => '42','name' => 'Волжск'),
            array('id' => '434','parentid' => '42','name' => 'Йошкар-Ола'),
            array('id' => '435','parentid' => '43','name' => 'Инсар'),
            array('id' => '436','parentid' => '43','name' => 'Ковылкино'),
            array('id' => '437','parentid' => '43','name' => 'Краснослободск'),
            array('id' => '438','parentid' => '43','name' => 'Рузаевка'),
            array('id' => '439','parentid' => '43','name' => 'Саранск'),
            array('id' => '440','parentid' => '44','name' => 'Агрыз'),
            array('id' => '441','parentid' => '44','name' => 'Азнакаево'),
            array('id' => '442','parentid' => '44','name' => 'Альметьевск'),
            array('id' => '443','parentid' => '44','name' => 'Арск'),
            array('id' => '444','parentid' => '44','name' => 'Бавлы'),
            array('id' => '445','parentid' => '44','name' => 'Бугульма'),
            array('id' => '446','parentid' => '44','name' => 'Буинск'),
            array('id' => '447','parentid' => '44','name' => 'Елабуга'),
            array('id' => '448','parentid' => '44','name' => 'Заинск'),
            array('id' => '449','parentid' => '44','name' => 'Зеленодольск'),
            array('id' => '450','parentid' => '44','name' => 'Казань'),
            array('id' => '451','parentid' => '44','name' => 'Лениногорск'),
            array('id' => '452','parentid' => '44','name' => 'Мамадыш'),
            array('id' => '453','parentid' => '44','name' => 'Менделеевск'),
            array('id' => '454','parentid' => '44','name' => 'Мензелинск'),
            array('id' => '455','parentid' => '44','name' => 'НабережныеЧелны'),
            array('id' => '456','parentid' => '44','name' => 'Нижнекамск'),
            array('id' => '457','parentid' => '44','name' => 'Нурлат'),
            array('id' => '458','parentid' => '44','name' => 'Тетюши'),
            array('id' => '459','parentid' => '45','name' => 'Воткинск'),
            array('id' => '460','parentid' => '45','name' => 'Глазов'),
            array('id' => '461','parentid' => '45','name' => 'Ижевск'),
            array('id' => '462','parentid' => '45','name' => 'Камбарка'),
            array('id' => '463','parentid' => '45','name' => 'Можга'),
            array('id' => '464','parentid' => '46','name' => 'Алатырь'),
            array('id' => '465','parentid' => '46','name' => 'Вурнары'),
            array('id' => '466','parentid' => '46','name' => 'Канаш'),
            array('id' => '467','parentid' => '46','name' => 'Козловка'),
            array('id' => '468','parentid' => '46','name' => 'МариинскийПосад'),
            array('id' => '469','parentid' => '46','name' => 'Новочебоксарск'),
            array('id' => '470','parentid' => '46','name' => 'Цивильск'),
            array('id' => '471','parentid' => '46','name' => 'Чебоксары'),
            array('id' => '472','parentid' => '46','name' => 'Шумерля'),
            array('id' => '473','parentid' => '47','name' => 'Заречный'),
            array('id' => '474','parentid' => '47','name' => 'Каменка'),
            array('id' => '475','parentid' => '47','name' => 'Кузнецк'),
            array('id' => '476','parentid' => '47','name' => 'НижнийЛомов'),
            array('id' => '477','parentid' => '47','name' => 'Никольск'),
            array('id' => '478','parentid' => '47','name' => 'Пенза'),
            array('id' => '479','parentid' => '47','name' => 'Сердобск'),
            array('id' => '480','parentid' => '47','name' => 'Спасск'),
            array('id' => '481','parentid' => '48','name' => 'Жигулёвск'),
            array('id' => '482','parentid' => '48','name' => 'Кинель'),
            array('id' => '483','parentid' => '48','name' => 'Нефтегорск'),
            array('id' => '484','parentid' => '48','name' => 'Новокуйбышевск'),
            array('id' => '485','parentid' => '48','name' => 'Октябрьск'),
            array('id' => '486','parentid' => '48','name' => 'Отрадный'),
            array('id' => '487','parentid' => '48','name' => 'Похвистнево'),
            array('id' => '488','parentid' => '48','name' => 'Самара'),
            array('id' => '489','parentid' => '48','name' => 'Сызрань'),
            array('id' => '490','parentid' => '48','name' => 'Тольятти'),
            array('id' => '491','parentid' => '49','name' => 'Аткарск'),
            array('id' => '492','parentid' => '49','name' => 'Балаково'),
            array('id' => '493','parentid' => '49','name' => 'Балашов'),
            array('id' => '494','parentid' => '49','name' => 'Вольск'),
            array('id' => '495','parentid' => '49','name' => 'Ершов'),
            array('id' => '496','parentid' => '49','name' => 'Калининск'),
            array('id' => '497','parentid' => '49','name' => 'Красноармейск'),
            array('id' => '498','parentid' => '49','name' => 'КрасныйКут'),
            array('id' => '499','parentid' => '49','name' => 'Маркс'),
            array('id' => '500','parentid' => '49','name' => 'Новоузенск'),
            array('id' => '501','parentid' => '49','name' => 'Петровск'),
            array('id' => '502','parentid' => '49','name' => 'Пугачёв'),
            array('id' => '503','parentid' => '49','name' => 'Ртищево'),
            array('id' => '504','parentid' => '49','name' => 'Саратов'),
            array('id' => '505','parentid' => '49','name' => 'Хвалынск'),
            array('id' => '506','parentid' => '49','name' => 'Шиханы'),
            array('id' => '507','parentid' => '50','name' => 'Димитровград'),
            array('id' => '508','parentid' => '50','name' => 'Инза'),
            array('id' => '509','parentid' => '50','name' => 'Новоульяновск'),
            array('id' => '510','parentid' => '50','name' => 'Сенгилей'),
            array('id' => '511','parentid' => '7','name' => 'Курганская область'),
            array('id' => '512','parentid' => '7','name' => 'Свердловская область'),
            array('id' => '513','parentid' => '7','name' => 'Тюменская область'),
            array('id' => '514','parentid' => '7','name' => 'Ханты-Мансийский АО-Югра'),
            array('id' => '515','parentid' => '7','name' => 'Ямало-Ненецкий АО'),
            array('id' => '516','parentid' => '7','name' => 'Челябинская область'),
            array('id' => '517','parentid' => '511','name' => 'Курган'),
            array('id' => '518','parentid' => '511','name' => 'Шадринск'),
            array('id' => '519','parentid' => '511','name' => 'Шумиха'),
            array('id' => '520','parentid' => '511','name' => 'Куртамыш'),
            array('id' => '521','parentid' => '511','name' => 'Далматово'),
            array('id' => '522','parentid' => '511','name' => 'Катайск'),
            array('id' => '523','parentid' => '511','name' => 'Петухово'),
            array('id' => '524','parentid' => '511','name' => 'Щучье'),
            array('id' => '525','parentid' => '511','name' => 'Макушино'),
            array('id' => '526','parentid' => '512','name' => 'Екатеринбург'),
            array('id' => '527','parentid' => '512','name' => 'Нижний Тагил'),
            array('id' => '528','parentid' => '512','name' => 'Каменск-Уральский'),
            array('id' => '529','parentid' => '512','name' => 'Первоуральск'),
            array('id' => '530','parentid' => '512','name' => 'Асбест'),
            array('id' => '531','parentid' => '512','name' => 'Берёзовский'),
            array('id' => '532','parentid' => '512','name' => 'Верхняя Пышма'),
            array('id' => '533','parentid' => '512','name' => 'Краснотурьинск'),
            array('id' => '534','parentid' => '512','name' => 'Лесной'),
            array('id' => '535','parentid' => '512','name' => 'Новоуральск'),
            array('id' => '536','parentid' => '512','name' => 'Полевской'),
            array('id' => '537','parentid' => '512','name' => 'Ревда'),
            array('id' => '538','parentid' => '512','name' => 'Серов'),
            array('id' => '539','parentid' => '512','name' => 'Алапаевск'),
            array('id' => '540','parentid' => '512','name' => 'Арамиль'),
            array('id' => '541','parentid' => '512','name' => 'Артёмовский'),
            array('id' => '542','parentid' => '512','name' => 'Богданович'),
            array('id' => '543','parentid' => '512','name' => 'Верхний Тагил'),
            array('id' => '544','parentid' => '512','name' => 'Верхняя Салда'),
            array('id' => '545','parentid' => '512','name' => 'Верхняя Тура'),
            array('id' => '546','parentid' => '512','name' => 'Верхотурье'),
            array('id' => '547','parentid' => '512','name' => 'Волчанск'),
            array('id' => '548','parentid' => '512','name' => 'Дегтярск'),
            array('id' => '549','parentid' => '512','name' => 'Заречный'),
            array('id' => '550','parentid' => '512','name' => 'Ивдель'),
            array('id' => '551','parentid' => '512','name' => 'Ирбит'),
            array('id' => '552','parentid' => '512','name' => 'Карпинск'),
            array('id' => '553','parentid' => '512','name' => 'Качканар'),
            array('id' => '554','parentid' => '512','name' => 'Красноуральск'),
            array('id' => '555','parentid' => '512','name' => 'Красноуфимск'),
            array('id' => '556','parentid' => '512','name' => 'Кушва'),
            array('id' => '557','parentid' => '512','name' => 'Михайловск'),
            array('id' => '558','parentid' => '512','name' => 'Невьянск'),
            array('id' => '559','parentid' => '512','name' => 'Нижние Серги'),
            array('id' => '560','parentid' => '512','name' => 'Нижняя Салд'),
            array('id' => '561','parentid' => '512','name' => 'Нижняя Тура'),
            array('id' => '562','parentid' => '512','name' => 'Новая Ляля'),
            array('id' => '563','parentid' => '512','name' => 'Реж'),
            array('id' => '564','parentid' => '512','name' => 'Североуральск'),
            array('id' => '565','parentid' => '512','name' => 'Среднеуральск'),
            array('id' => '566','parentid' => '512','name' => 'Сухой Лог'),
            array('id' => '567','parentid' => '512','name' => 'Сысерть'),
            array('id' => '568','parentid' => '512','name' => 'Тавда'),
            array('id' => '569','parentid' => '512','name' => 'Талица'),
            array('id' => '570','parentid' => '512','name' => 'Туринск'),
            array('id' => '571','parentid' => '513','name' => 'Тюмень'),
            array('id' => '572','parentid' => '513','name' => 'Ишим'),
            array('id' => '573','parentid' => '513','name' => 'Тобольск'),
            array('id' => '574','parentid' => '513','name' => 'Заводоуковск'),
            array('id' => '575','parentid' => '513','name' => 'Ялуторовск'),
            array('id' => '576','parentid' => '514','name' => 'Нижневартовск'),
            array('id' => '577','parentid' => '514','name' => 'Сургут'),
            array('id' => '578','parentid' => '514','name' => 'Нефтеюганск'),
            array('id' => '579','parentid' => '514','name' => 'Когалым'),
            array('id' => '580','parentid' => '514','name' => 'Нягань'),
            array('id' => '581','parentid' => '514','name' => 'Ханты-Мансийск'),
            array('id' => '582','parentid' => '514','name' => 'Белоярский'),
            array('id' => '583','parentid' => '514','name' => 'Лангепас'),
            array('id' => '584','parentid' => '514','name' => 'Лянтор'),
            array('id' => '585','parentid' => '514','name' => 'Мегион'),
            array('id' => '586','parentid' => '514','name' => 'Покачи'),
            array('id' => '587','parentid' => '514','name' => 'Пыть-Ях'),
            array('id' => '588','parentid' => '514','name' => 'Радужный'),
            array('id' => '589','parentid' => '514','name' => 'Советский'),
            array('id' => '590','parentid' => '514','name' => 'Урай'),
            array('id' => '591','parentid' => '514','name' => 'Югорск'),
            array('id' => '592','parentid' => '515','name' => 'Новый Уренгой'),
            array('id' => '593','parentid' => '515','name' => 'Ноябрьск'),
            array('id' => '594','parentid' => '515','name' => 'Губкинский'),
            array('id' => '595','parentid' => '515','name' => 'Лабытнанги'),
            array('id' => '596','parentid' => '515','name' => 'Муравленко'),
            array('id' => '597','parentid' => '515','name' => 'Надым'),
            array('id' => '598','parentid' => '515','name' => 'Салехард'),
            array('id' => '599','parentid' => '515','name' => 'Тарко-Сале'),
            array('id' => '600','parentid' => '516','name' => 'Челябинск'),
            array('id' => '601','parentid' => '516','name' => 'Магнитогорск'),
            array('id' => '602','parentid' => '516','name' => 'Златоуст'),
            array('id' => '603','parentid' => '516','name' => 'Копейск'),
            array('id' => '604','parentid' => '516','name' => 'Миасс'),
            array('id' => '605','parentid' => '516','name' => 'Озёрск'),
            array('id' => '606','parentid' => '516','name' => 'Троицк'),
            array('id' => '607','parentid' => '516','name' => 'Аша'),
            array('id' => '608','parentid' => '516','name' => 'Бакал'),
            array('id' => '609','parentid' => '516','name' => 'Верхнеуральск'),
            array('id' => '610','parentid' => '516','name' => 'Верхний Уфалей'),
            array('id' => '611','parentid' => '516','name' => 'Еманжелинск'),
            array('id' => '612','parentid' => '516','name' => 'Карабаш'),
            array('id' => '613','parentid' => '516','name' => 'Карталы'),
            array('id' => '614','parentid' => '516','name' => 'Касли'),
            array('id' => '615','parentid' => '516','name' => 'Катав-Ивановск'),
            array('id' => '616','parentid' => '516','name' => 'Коркино'),
            array('id' => '617','parentid' => '516','name' => 'Куса'),
            array('id' => '618','parentid' => '516','name' => 'Кыштым'),
            array('id' => '619','parentid' => '516','name' => 'Миньяр'),
            array('id' => '620','parentid' => '516','name' => 'Нязепетровск'),
            array('id' => '621','parentid' => '516','name' => 'Пласт'),
            array('id' => '622','parentid' => '516','name' => 'Сатка'),
            array('id' => '623','parentid' => '516','name' => 'Сим'),
            array('id' => '624','parentid' => '516','name' => 'Снежинск'),
            array('id' => '625','parentid' => '516','name' => 'Трёхгорный'),
            array('id' => '626','parentid' => '516','name' => 'Усть-Катав'),
            array('id' => '627','parentid' => '516','name' => 'Чебаркуль'),
            array('id' => '628','parentid' => '516','name' => 'Южноуральск'),
            array('id' => '629','parentid' => '516','name' => 'Юрюзань'),
            array('id' => '630','parentid' => '6','name' => 'Пермский край'),
            array('id' => '631','parentid' => '630','name' => 'Пермь'),
            array('id' => '632','parentid' => '630','name' => 'Березники'),
            array('id' => '633','parentid' => '630','name' => 'Соликамск'),
            array('id' => '634','parentid' => '630','name' => 'Чайковский'),
            array('id' => '635','parentid' => '630','name' => 'Кунгур'),
            array('id' => '636','parentid' => '630','name' => 'Лысьва'),
            array('id' => '637','parentid' => '630','name' => 'Краснокамск'),
            array('id' => '638','parentid' => '630','name' => 'Чусовой'),
            array('id' => '639','parentid' => '630','name' => 'Чернушка'),
            array('id' => '640','parentid' => '630','name' => 'Добрянка'),
            array('id' => '641','parentid' => '630','name' => 'Кудымкар'),
            array('id' => '642','parentid' => '630','name' => 'Губаха'),
            array('id' => '643','parentid' => '630','name' => 'Верещагино'),
            array('id' => '644','parentid' => '630','name' => 'Оса'),
            array('id' => '645','parentid' => '630','name' => 'Нытва'),
            array('id' => '646','parentid' => '630','name' => 'Кизел'),
            array('id' => '647','parentid' => '630','name' => 'Кондратово'),
            array('id' => '648','parentid' => '630','name' => 'Красновишерск'),
            array('id' => '649','parentid' => '630','name' => 'Очёр'),
            array('id' => '650','parentid' => '630','name' => 'Полазна'),
            array('id' => '651','parentid' => '630','name' => 'Горнозаводск'),
            array('id' => '652','parentid' => '630','name' => 'Александровск'),
            array('id' => '653','parentid' => '4','name' => 'Адыгея'),
            array('id' => '654','parentid' => '4','name' => 'Астраханская область'),
            array('id' => '655','parentid' => '4','name' => 'Республика Калмыкия'),
            array('id' => '656','parentid' => '4','name' => 'Волгоградская область'),
            array('id' => '657','parentid' => '4','name' => 'Краснодарский край'),
            array('id' => '658','parentid' => '4','name' => 'Республика Крым'),
            array('id' => '659','parentid' => '4','name' => 'Ростовская область'),
            array('id' => '660','parentid' => '4','name' => 'Севастополь'),
            array('id' => '661','parentid' => '653','name' => 'Майкоп'),
            array('id' => '662','parentid' => '653','name' => 'Адыгейск'),
            array('id' => '663','parentid' => '654','name' => 'Астрахань'),
            array('id' => '664','parentid' => '654','name' => 'Ахтубинск'),
            array('id' => '665','parentid' => '654','name' => 'Знаменск'),
            array('id' => '666','parentid' => '654','name' => 'Камызяк'),
            array('id' => '667','parentid' => '654','name' => 'Нариманов'),
            array('id' => '668','parentid' => '654','name' => 'Харабали'),
            array('id' => '669','parentid' => '655','name' => 'Волгоград'),
            array('id' => '670','parentid' => '655','name' => 'Волжский'),
            array('id' => '671','parentid' => '655','name' => 'Камышин'),
            array('id' => '672','parentid' => '655','name' => 'Михайловка'),
            array('id' => '673','parentid' => '655','name' => 'Дубовка'),
            array('id' => '674','parentid' => '655','name' => 'Жирновск'),
            array('id' => '675','parentid' => '655','name' => 'Калач-на-Дону'),
            array('id' => '676','parentid' => '655','name' => 'Котельниково'),
            array('id' => '677','parentid' => '655','name' => 'Котово'),
            array('id' => '678','parentid' => '655','name' => 'Краснослободск'),
            array('id' => '679','parentid' => '655','name' => 'Ленинск'),
            array('id' => '680','parentid' => '655','name' => 'Николаевск'),
            array('id' => '681','parentid' => '655','name' => 'Новоаннинский'),
            array('id' => '682','parentid' => '655','name' => 'Палласовка'),
            array('id' => '683','parentid' => '655','name' => 'Петров Вал'),
            array('id' => '684','parentid' => '655','name' => 'Серафимович'),
            array('id' => '685','parentid' => '655','name' => 'Суровикино'),
            array('id' => '686','parentid' => '655','name' => 'Урюпинск'),
            array('id' => '687','parentid' => '655','name' => 'Фролово'),
            array('id' => '688','parentid' => '656','name' => 'Элиста'),
            array('id' => '689','parentid' => '656','name' => 'Городовиковск'),
            array('id' => '690','parentid' => '656','name' => 'Лагань'),
            array('id' => '691','parentid' => '657','name' => 'Краснодар'),
            array('id' => '692','parentid' => '657','name' => 'Сочи'),
            array('id' => '693','parentid' => '657','name' => 'Армавир'),
            array('id' => '694','parentid' => '657','name' => 'Новороссийск'),
            array('id' => '695','parentid' => '657','name' => 'Анапа'),
            array('id' => '696','parentid' => '657','name' => 'Белореченск'),
            array('id' => '697','parentid' => '657','name' => 'Геленджик'),
            array('id' => '698','parentid' => '657','name' => 'Ейск'),
            array('id' => '699','parentid' => '657','name' => 'Кропоткин'),
            array('id' => '700','parentid' => '657','name' => 'Крымск'),
            array('id' => '701','parentid' => '657','name' => 'Лабинск'),
            array('id' => '702','parentid' => '657','name' => 'Славянск-на-Кубани'),
            array('id' => '703','parentid' => '657','name' => 'Тимашёвск'),
            array('id' => '704','parentid' => '657','name' => 'Тихорецк'),
            array('id' => '705','parentid' => '657','name' => 'Туапсе'),
            array('id' => '706','parentid' => '657','name' => 'Абинск'),
            array('id' => '707','parentid' => '657','name' => 'Апшеронск'),
            array('id' => '708','parentid' => '657','name' => 'Горячий Ключ'),
            array('id' => '709','parentid' => '657','name' => 'Гулькевичи'),
            array('id' => '710','parentid' => '657','name' => 'Кореновск'),
            array('id' => '711','parentid' => '657','name' => 'Курганинск'),
            array('id' => '712','parentid' => '657','name' => 'Новокубанск'),
            array('id' => '713','parentid' => '657','name' => 'Приморско-Ахтарск'),
            array('id' => '714','parentid' => '657','name' => 'Темрюк'),
            array('id' => '715','parentid' => '657','name' => 'Усть-Лабинск'),
            array('id' => '716','parentid' => '657','name' => 'Хадыженск'),
            array('id' => '717','parentid' => '658','name' => 'Симферополь'),
            array('id' => '718','parentid' => '658','name' => 'Керчь'),
            array('id' => '719','parentid' => '658','name' => 'Евпатория'),
            array('id' => '720','parentid' => '658','name' => 'Ялта'),
            array('id' => '721','parentid' => '658','name' => 'Феодосия'),
            array('id' => '722','parentid' => '658','name' => 'Джанкой'),
            array('id' => '723','parentid' => '658','name' => 'Алушта'),
            array('id' => '724','parentid' => '658','name' => 'Бахчисарай'),
            array('id' => '725','parentid' => '658','name' => 'Красноперекопск'),
            array('id' => '726','parentid' => '658','name' => 'Саки'),
            array('id' => '727','parentid' => '658','name' => 'Армянск'),
            array('id' => '728','parentid' => '658','name' => 'Судак'),
            array('id' => '729','parentid' => '658','name' => 'Белогорск'),
            array('id' => '730','parentid' => '658','name' => 'Щёлкино'),
            array('id' => '731','parentid' => '658','name' => 'Старый Крым'),
            array('id' => '732','parentid' => '658','name' => 'Алупка'),
            array('id' => '733','parentid' => '659','name' => 'Ростов-на-Дону'),
            array('id' => '734','parentid' => '659','name' => 'Таганрог'),
            array('id' => '735','parentid' => '659','name' => 'Батайск'),
            array('id' => '736','parentid' => '659','name' => 'Волгодонск'),
            array('id' => '737','parentid' => '659','name' => 'Новочеркасск'),
            array('id' => '738','parentid' => '659','name' => 'Новошахтинск'),
            array('id' => '739','parentid' => '659','name' => 'Шахты'),
            array('id' => '740','parentid' => '659','name' => 'Азов'),
            array('id' => '741','parentid' => '659','name' => 'Гуково'),
            array('id' => '742','parentid' => '659','name' => 'Донецк'),
            array('id' => '743','parentid' => '659','name' => 'Каменск-Шахтинский'),
            array('id' => '744','parentid' => '659','name' => 'Сальск'),
            array('id' => '745','parentid' => '659','name' => 'Аксай'),
            array('id' => '746','parentid' => '659','name' => 'Белая Калитва'),
            array('id' => '747','parentid' => '659','name' => 'Зверево'),
            array('id' => '748','parentid' => '659','name' => 'Зерноград'),
            array('id' => '749','parentid' => '659','name' => 'Константиновск'),
            array('id' => '750','parentid' => '659','name' => 'Красный Сулин'),
            array('id' => '751','parentid' => '659','name' => 'Миллерово'),
            array('id' => '752','parentid' => '659','name' => 'Морозовск'),
            array('id' => '753','parentid' => '659','name' => 'Пролетарск'),
            array('id' => '754','parentid' => '659','name' => 'Семикаракорск'),
            array('id' => '755','parentid' => '659','name' => 'Цимлянск'),
            array('id' => '756','parentid' => '660','name' => 'Севастополь'),
            array('id' => '757','parentid' => '660','name' => 'Инкерман'),
            array('id' => '758','parentid' => '5','name' => 'Дагестан'),
            array('id' => '759','parentid' => '5','name' => 'Ингушетия'),
            array('id' => '760','parentid' => '5','name' => 'Кабардино-Балкария'),
            array('id' => '761','parentid' => '5','name' => 'Карачаево-Черкесия'),
            array('id' => '762','parentid' => '5','name' => 'Северная Осетия'),
            array('id' => '763','parentid' => '5','name' => 'Ставропольский край'),
            array('id' => '764','parentid' => '5','name' => 'Чечня'),
            array('id' => '765','parentid' => '758','name' => 'Дербент'),
            array('id' => '766','parentid' => '758','name' => 'Каспийск'),
            array('id' => '767','parentid' => '758','name' => 'Буйнакск'),
            array('id' => '768','parentid' => '758','name' => 'Избербаш'),
            array('id' => '769','parentid' => '758','name' => 'Кизляр'),
            array('id' => '770','parentid' => '758','name' => 'Кизилюрт'),
            array('id' => '771','parentid' => '758','name' => 'Дагестанские Огни'),
            array('id' => '772','parentid' => '758','name' => 'Южно-Сухокумск'),
            array('id' => '773','parentid' => '759','name' => 'Назрань'),
            array('id' => '774','parentid' => '759','name' => 'Сунжа'),
            array('id' => '775','parentid' => '759','name' => 'Карабулак'),
            array('id' => '776','parentid' => '759','name' => 'Малгобек'),
            array('id' => '777','parentid' => '759','name' => 'Магас'),
            array('id' => '778','parentid' => '760','name' => 'Нальчик'),
            array('id' => '779','parentid' => '760','name' => 'Прохладный'),
            array('id' => '780','parentid' => '760','name' => 'Баксан'),
            array('id' => '781','parentid' => '760','name' => 'Нарткала'),
            array('id' => '782','parentid' => '760','name' => 'Майский'),
            array('id' => '783','parentid' => '760','name' => 'Тырныауз'),
            array('id' => '784','parentid' => '760','name' => 'Чегем'),
            array('id' => '785','parentid' => '760','name' => 'Терек'),
            array('id' => '786','parentid' => '761','name' => 'Черкесск'),
            array('id' => '787','parentid' => '761','name' => 'Усть-Джегута'),
            array('id' => '788','parentid' => '761','name' => 'Карачаевск'),
            array('id' => '789','parentid' => '761','name' => 'Теберда'),
            array('id' => '790','parentid' => '762','name' => 'Владикавказ'),
            array('id' => '791','parentid' => '762','name' => 'Беслан'),
            array('id' => '792','parentid' => '762','name' => 'Моздок'),
            array('id' => '793','parentid' => '762','name' => 'Алагир'),
            array('id' => '794','parentid' => '762','name' => 'Ардон'),
            array('id' => '795','parentid' => '762','name' => 'Дигора'),
            array('id' => '796','parentid' => '763','name' => 'Ставрополь'),
            array('id' => '797','parentid' => '763','name' => 'Пятигорск'),
            array('id' => '798','parentid' => '763','name' => 'Кисловодск'),
            array('id' => '799','parentid' => '763','name' => 'Ессентуки'),
            array('id' => '800','parentid' => '763','name' => 'Невинномысск'),
            array('id' => '801','parentid' => '763','name' => 'Михайловск'),
            array('id' => '802','parentid' => '763','name' => 'Минеральные Воды'),
            array('id' => '803','parentid' => '763','name' => 'Георгиевск'),
            array('id' => '804','parentid' => '763','name' => 'Будённовск'),
            array('id' => '805','parentid' => '763','name' => 'Изобильный'),
            array('id' => '806','parentid' => '763','name' => 'Светлоград'),
            array('id' => '807','parentid' => '763','name' => 'Зеленокумск'),
            array('id' => '808','parentid' => '763','name' => 'Благодарный'),
            array('id' => '809','parentid' => '763','name' => 'Новоалександровск'),
            array('id' => '810','parentid' => '763','name' => 'Ипатово'),
            array('id' => '811','parentid' => '763','name' => 'Нефтекумск'),
            array('id' => '812','parentid' => '763','name' => 'Лермонтов'),
            array('id' => '813','parentid' => '763','name' => 'Железноводск'),
            array('id' => '814','parentid' => '763','name' => 'Новопавловск'),
            array('id' => '815','parentid' => '764','name' => 'Грозный'),
            array('id' => '816','parentid' => '764','name' => 'Гудермес'),
            array('id' => '817','parentid' => '764','name' => 'Урус-Мартан'),
            array('id' => '818','parentid' => '764','name' => 'Шали'),
            array('id' => '819','parentid' => '764','name' => 'Аргун'),
            array('id' => '820','parentid' => '764','name' => 'Ачхой-Мартан'),
            array('id' => '821','parentid' => '8','name' => 'Республика Алтай'),
            array('id' => '822','parentid' => '8','name' => 'Алтайский край'),
            array('id' => '823','parentid' => '8','name' => 'Иркутская область'),
            array('id' => '824','parentid' => '8','name' => 'Кемеровская область'),
            array('id' => '825','parentid' => '8','name' => 'Красноярский край'),
            array('id' => '826','parentid' => '8','name' => 'Новосибирская область'),
            array('id' => '827','parentid' => '8','name' => 'Омская область'),
            array('id' => '828','parentid' => '8','name' => 'Томская область'),
            array('id' => '829','parentid' => '8','name' => 'Тува'),
            array('id' => '830','parentid' => '8','name' => 'Хакасия'),
            array('id' => '831','parentid' => '821','name' => 'Горно-Алтайск'),
            array('id' => '832','parentid' => '821','name' => 'Новоалтайск'),
            array('id' => '833','parentid' => '821','name' => 'Алейск'),
            array('id' => '834','parentid' => '821','name' => 'Белокуриха'),
            array('id' => '835','parentid' => '821','name' => 'Горняк'),
            array('id' => '836','parentid' => '821','name' => 'Заринск'),
            array('id' => '837','parentid' => '821','name' => 'Змеиногорск'),
            array('id' => '838','parentid' => '821','name' => 'Камень-на-Оби'),
            array('id' => '839','parentid' => '821','name' => 'Славгород'),
            array('id' => '840','parentid' => '821','name' => 'Яровое'),
            array('id' => '841','parentid' => '822','name' => 'Барнаул'),
            array('id' => '842','parentid' => '822','name' => 'Бийск'),
            array('id' => '843','parentid' => '822','name' => 'Рубцовск'),
            array('id' => '844','parentid' => '823','name' => 'Иркутск'),
            array('id' => '845','parentid' => '823','name' => 'Ангарск'),
            array('id' => '846','parentid' => '823','name' => 'Братск'),
            array('id' => '847','parentid' => '823','name' => 'Усолье-Сибирское'),
            array('id' => '848','parentid' => '823','name' => 'Усть-Илимск'),
            array('id' => '849','parentid' => '823','name' => 'Черемхово'),
            array('id' => '850','parentid' => '823','name' => 'Алзамай'),
            array('id' => '851','parentid' => '823','name' => 'Байкальск'),
            array('id' => '852','parentid' => '823','name' => 'Бирюсинск'),
            array('id' => '853','parentid' => '823','name' => 'Бодайбо'),
            array('id' => '854','parentid' => '823','name' => 'Вихоревка'),
            array('id' => '855','parentid' => '823','name' => 'Железногорск-Илимский'),
            array('id' => '856','parentid' => '823','name' => 'Зима'),
            array('id' => '857','parentid' => '823','name' => 'Киренск'),
            array('id' => '858','parentid' => '823','name' => 'Нижнеудинск'),
            array('id' => '859','parentid' => '823','name' => 'Саянск'),
            array('id' => '860','parentid' => '823','name' => 'Свирск'),
            array('id' => '861','parentid' => '823','name' => 'Слюдянка'),
            array('id' => '862','parentid' => '823','name' => 'Тайшет'),
            array('id' => '863','parentid' => '823','name' => 'Тулун'),
            array('id' => '864','parentid' => '823','name' => 'Усть-Кут'),
            array('id' => '865','parentid' => '823','name' => 'Шелехов'),
            array('id' => '866','parentid' => '824','name' => 'Кемерово'),
            array('id' => '867','parentid' => '824','name' => 'Новокузнецк'),
            array('id' => '868','parentid' => '824','name' => 'Прокопьевск'),
            array('id' => '869','parentid' => '824','name' => 'Междуреченск'),
            array('id' => '870','parentid' => '824','name' => 'Ленинск-Кузнецкий'),
            array('id' => '871','parentid' => '824','name' => 'Киселёвск'),
            array('id' => '872','parentid' => '824','name' => 'Юрга'),
            array('id' => '873','parentid' => '824','name' => 'Анжеро-Судженск'),
            array('id' => '874','parentid' => '824','name' => 'Белово'),
            array('id' => '875','parentid' => '824','name' => 'Берёзовский'),
            array('id' => '876','parentid' => '824','name' => 'Осинники'),
            array('id' => '877','parentid' => '824','name' => 'Мыски'),
            array('id' => '878','parentid' => '824','name' => 'Мариинск'),
            array('id' => '879','parentid' => '824','name' => 'Топки'),
            array('id' => '880','parentid' => '824','name' => 'Полысаево'),
            array('id' => '881','parentid' => '824','name' => 'Тайга'),
            array('id' => '882','parentid' => '824','name' => 'Гурьевск'),
            array('id' => '883','parentid' => '824','name' => 'Таштагол'),
            array('id' => '884','parentid' => '824','name' => 'Калтан'),
            array('id' => '885','parentid' => '825','name' => 'Красноярск'),
            array('id' => '886','parentid' => '825','name' => 'Ачинск'),
            array('id' => '887','parentid' => '825','name' => 'Норильск'),
            array('id' => '888','parentid' => '825','name' => 'Железногорск'),
            array('id' => '889','parentid' => '825','name' => 'Зеленогорск'),
            array('id' => '890','parentid' => '825','name' => 'Канск'),
            array('id' => '891','parentid' => '825','name' => 'Лесосибирск'),
            array('id' => '892','parentid' => '825','name' => 'Минусинск'),
            array('id' => '893','parentid' => '825','name' => 'Назарово'),
            array('id' => '894','parentid' => '825','name' => 'Артёмовск'),
            array('id' => '895','parentid' => '825','name' => 'Боготол'),
            array('id' => '896','parentid' => '825','name' => 'Бородино'),
            array('id' => '897','parentid' => '825','name' => 'Дивногорск'),
            array('id' => '898','parentid' => '825','name' => 'Дудинка'),
            array('id' => '899','parentid' => '825','name' => 'Енисейск'),
            array('id' => '900','parentid' => '825','name' => 'Заозёрный'),
            array('id' => '901','parentid' => '825','name' => 'Игарка'),
            array('id' => '902','parentid' => '825','name' => 'Иланский'),
            array('id' => '903','parentid' => '825','name' => 'Кодинск'),
            array('id' => '904','parentid' => '825','name' => 'Сосновоборск'),
            array('id' => '905','parentid' => '825','name' => 'Ужур'),
            array('id' => '906','parentid' => '825','name' => 'Уяр'),
            array('id' => '907','parentid' => '825','name' => 'Шарыпово'),
            array('id' => '908','parentid' => '826','name' => 'Новосибирск'),
            array('id' => '909','parentid' => '826','name' => 'Бердск'),
            array('id' => '910','parentid' => '826','name' => 'Искитим'),
            array('id' => '911','parentid' => '826','name' => 'Барабинск'),
            array('id' => '912','parentid' => '826','name' => 'Болотное'),
            array('id' => '913','parentid' => '826','name' => 'Карасук'),
            array('id' => '914','parentid' => '826','name' => 'Каргат'),
            array('id' => '915','parentid' => '826','name' => 'Куйбышев'),
            array('id' => '916','parentid' => '826','name' => 'Купино'),
            array('id' => '917','parentid' => '826','name' => 'Обь'),
            array('id' => '918','parentid' => '826','name' => 'Татарск'),
            array('id' => '919','parentid' => '826','name' => 'Тогучин'),
            array('id' => '920','parentid' => '826','name' => 'Черепаново'),
            array('id' => '921','parentid' => '826','name' => 'Чулым'),
            array('id' => '922','parentid' => '827','name' => 'Омск'),
            array('id' => '923','parentid' => '827','name' => 'Исилькуль'),
            array('id' => '924','parentid' => '827','name' => 'Калачинск'),
            array('id' => '925','parentid' => '827','name' => 'Называевск'),
            array('id' => '926','parentid' => '827','name' => 'Тара'),
            array('id' => '927','parentid' => '827','name' => 'Тюкалинск'),
            array('id' => '928','parentid' => '828','name' => 'Томск'),
            array('id' => '929','parentid' => '828','name' => 'Северск'),
            array('id' => '930','parentid' => '828','name' => 'Асино'),
            array('id' => '931','parentid' => '828','name' => 'Кедровый'),
            array('id' => '932','parentid' => '828','name' => 'Колпашево'),
            array('id' => '933','parentid' => '828','name' => 'Стрежевой'),
            array('id' => '934','parentid' => '829','name' => 'Кызыл'),
            array('id' => '935','parentid' => '829','name' => 'Ак-Довурак'),
            array('id' => '936','parentid' => '829','name' => 'Туран'),
            array('id' => '937','parentid' => '829','name' => 'Чадан'),
            array('id' => '938','parentid' => '829','name' => 'Шагонар'),
            array('id' => '939','parentid' => '830','name' => 'Абакан'),
            array('id' => '940','parentid' => '830','name' => 'Черногорск'),
            array('id' => '941','parentid' => '830','name' => 'Абаза'),
            array('id' => '942','parentid' => '830','name' => 'Саяногорск'),
            array('id' => '943','parentid' => '830','name' => 'Сорск'),
            array('id' => '944','parentid' => '9','name' => 'Амурская область'),
            array('id' => '945','parentid' => '9','name' => 'Бурятия'),
            array('id' => '946','parentid' => '9','name' => 'Еврейская автономная область'),
            array('id' => '947','parentid' => '9','name' => 'Забайкальский край'),
            array('id' => '948','parentid' => '9','name' => 'Камчатский край'),
            array('id' => '949','parentid' => '9','name' => 'Магаданская область'),
            array('id' => '950','parentid' => '9','name' => 'Приморский край'),
            array('id' => '951','parentid' => '9','name' => 'Саха (Якутия)'),
            array('id' => '952','parentid' => '9','name' => 'Сахалинская область'),
            array('id' => '953','parentid' => '9','name' => 'Хабаровский край'),
            array('id' => '954','parentid' => '9','name' => 'Чукотский автономный округ'),
            array('id' => '955','parentid' => '944','name' => 'Благовещенск'),
            array('id' => '956','parentid' => '944','name' => 'Белогорск'),
            array('id' => '957','parentid' => '944','name' => 'Свободный'),
            array('id' => '958','parentid' => '944','name' => 'Тында'),
            array('id' => '959','parentid' => '944','name' => 'Зея'),
            array('id' => '960','parentid' => '944','name' => 'Шимановск'),
            array('id' => '961','parentid' => '944','name' => 'Райчихинск'),
            array('id' => '962','parentid' => '944','name' => 'Завитинск'),
            array('id' => '963','parentid' => '944','name' => 'Сковородино'),
            array('id' => '964','parentid' => '945','name' => 'Улан-Удэ'),
            array('id' => '965','parentid' => '945','name' => 'Северобайкальск'),
            array('id' => '966','parentid' => '945','name' => 'Гусиноозёрск'),
            array('id' => '967','parentid' => '945','name' => 'Кяхта'),
            array('id' => '968','parentid' => '945','name' => 'Закаменск'),
            array('id' => '969','parentid' => '945','name' => 'Бабушкин'),
            array('id' => '970','parentid' => '946','name' => 'Биробиджан'),
            array('id' => '971','parentid' => '946','name' => 'Облучье'),
            array('id' => '972','parentid' => '947','name' => 'Чита'),
            array('id' => '973','parentid' => '947','name' => 'Краснокаменск'),
            array('id' => '974','parentid' => '947','name' => 'Борзя'),
            array('id' => '975','parentid' => '947','name' => 'Петровск-Забайкальский'),
            array('id' => '976','parentid' => '947','name' => 'Нерчинск'),
            array('id' => '977','parentid' => '947','name' => 'Могоча'),
            array('id' => '978','parentid' => '947','name' => 'Шилка'),
            array('id' => '979','parentid' => '947','name' => 'Балей'),
            array('id' => '980','parentid' => '947','name' => 'Хилок'),
            array('id' => '981','parentid' => '947','name' => 'Сретенск'),
            array('id' => '982','parentid' => '948','name' => 'Петропавловск-Камчатский'),
            array('id' => '983','parentid' => '948','name' => 'Елизово'),
            array('id' => '984','parentid' => '948','name' => 'Вилючинск'),
            array('id' => '985','parentid' => '949','name' => 'Магадан'),
            array('id' => '986','parentid' => '949','name' => 'Сусуман'),
            array('id' => '987','parentid' => '950','name' => 'Владивосток'),
            array('id' => '988','parentid' => '950','name' => 'Уссурийск'),
            array('id' => '989','parentid' => '950','name' => 'Находка'),
            array('id' => '990','parentid' => '950','name' => 'Артём'),
            array('id' => '991','parentid' => '950','name' => 'Арсеньев'),
            array('id' => '992','parentid' => '950','name' => 'Спасск-Дальний'),
            array('id' => '993','parentid' => '950','name' => 'Большой Камень'),
            array('id' => '994','parentid' => '950','name' => 'Партизанск'),
            array('id' => '995','parentid' => '950','name' => 'Лесозаводск'),
            array('id' => '996','parentid' => '950','name' => 'Дальнегорск'),
            array('id' => '997','parentid' => '950','name' => 'Дальнереченск'),
            array('id' => '998','parentid' => '950','name' => 'Фокино'),
            array('id' => '999','parentid' => '951','name' => 'Якутск'),
            array('id' => '1000','parentid' => '951','name' => 'Нерюнгри'),
            array('id' => '1001','parentid' => '951','name' => 'Мирный'),
            array('id' => '1002','parentid' => '951','name' => 'Ленск'),
            array('id' => '1003','parentid' => '951','name' => 'Удачный'),
            array('id' => '1004','parentid' => '951','name' => 'Вилюйск'),
            array('id' => '1005','parentid' => '951','name' => 'Нюрба'),
            array('id' => '1006','parentid' => '951','name' => 'Покровск'),
            array('id' => '1007','parentid' => '951','name' => 'Олёкминск'),
            array('id' => '1008','parentid' => '951','name' => 'Томмот'),
            array('id' => '1009','parentid' => '951','name' => 'Среднеколымск'),
            array('id' => '1010','parentid' => '951','name' => 'Верхоянск'),
            array('id' => '1011','parentid' => '952','name' => 'Южно-Сахалинск'),
            array('id' => '1012','parentid' => '952','name' => 'Корсаков'),
            array('id' => '1013','parentid' => '952','name' => 'Холмск'),
            array('id' => '1014','parentid' => '952','name' => 'Оха'),
            array('id' => '1015','parentid' => '952','name' => 'Поронайск'),
            array('id' => '1016','parentid' => '952','name' => 'Долинск'),
            array('id' => '1017','parentid' => '952','name' => 'Невельск'),
            array('id' => '1018','parentid' => '952','name' => 'Анива'),
            array('id' => '1019','parentid' => '952','name' => 'Александровск-Сахалинский'),
            array('id' => '1020','parentid' => '952','name' => 'Углегорск'),
            array('id' => '1021','parentid' => '952','name' => 'Шахтёрск'),
            array('id' => '1022','parentid' => '952','name' => 'Макаров'),
            array('id' => '1023','parentid' => '952','name' => 'Томари'),
            array('id' => '1024','parentid' => '952','name' => 'Северо-Курильск'),
            array('id' => '1025','parentid' => '952','name' => 'Курильск'),
            array('id' => '1026','parentid' => '953','name' => 'Хабаровск'),
            array('id' => '1027','parentid' => '953','name' => 'Комсомольск-на-Амуре'),
            array('id' => '1028','parentid' => '953','name' => 'Амурск'),
            array('id' => '1029','parentid' => '953','name' => 'Советская Гавань'),
            array('id' => '1030','parentid' => '953','name' => 'Николаевск-на-Амуре'),
            array('id' => '1031','parentid' => '953','name' => 'Бикин'),
            array('id' => '1032','parentid' => '953','name' => 'Вяземский'),
            array('id' => '1033','parentid' => '954','name' => 'Анадырь'),
            array('id' => '1034','parentid' => '954','name' => 'Билибино'),
            array('id' => '1035','parentid' => '954','name' => 'Певек'),
            array('id' => '1036','parentid' => '13','name' => 'Череповец'),
            array('id' => '1037','parentid' => '6','name' => 'Нижегородская область'),
            array('id' => '1038','parentid' => '6','name' => 'Оренбургская область'),
            array('id' => '1039','parentid' => '1037','name' => 'Шахунья'),
            array('id' => '1040','parentid' => '1037','name' => 'Ардатов'),
            array('id' => '1041','parentid' => '1037','name' => 'Арзамас'),
            array('id' => '1042','parentid' => '1037','name' => 'Балахна'),
            array('id' => '1043','parentid' => '1037','name' => 'Богородск'),
            array('id' => '1044','parentid' => '1037','name' => 'Бор'),
            array('id' => '1045','parentid' => '1037','name' => 'Ветлуга'),
            array('id' => '1046','parentid' => '1037','name' => 'Ворсма'),
            array('id' => '1047','parentid' => '1037','name' => 'Выкса'),
            array('id' => '1048','parentid' => '1037','name' => 'Городец'),
            array('id' => '1049','parentid' => '1037','name' => 'Дзержинск'),
            array('id' => '1050','parentid' => '1037','name' => 'Заволжье'),
            array('id' => '1051','parentid' => '1037','name' => 'Княгинино'),
            array('id' => '1052','parentid' => '1037','name' => 'Кстово'),
            array('id' => '1053','parentid' => '1037','name' => 'Кулебаки'),
            array('id' => '1054','parentid' => '1037','name' => 'Лукоянов'),
            array('id' => '1055','parentid' => '1037','name' => 'Лысково'),
            array('id' => '1056','parentid' => '1037','name' => 'Навашино'),
            array('id' => '1057','parentid' => '1037','name' => 'Нижний Новгород'),
            array('id' => '1058','parentid' => '1037','name' => 'Павлово'),
            array('id' => '1059','parentid' => '1037','name' => 'Первомайск'),
            array('id' => '1060','parentid' => '1037','name' => 'Саров'),
            array('id' => '1061','parentid' => '1037','name' => 'Семёнов'),
            array('id' => '1062','parentid' => '1037','name' => 'Сергач'),
            array('id' => '1063','parentid' => '1037','name' => 'Урень'),
            array('id' => '1064','parentid' => '1037','name' => 'Чкаловск'),
            array('id' => '1065','parentid' => '1038','name' => 'Оренбург'),
            array('id' => '1066','parentid' => '1038','name' => 'Орск'),
            array('id' => '1067','parentid' => '1038','name' => 'Бузулук'),
            array('id' => '1068','parentid' => '1038','name' => 'Новотроицк'),
            array('id' => '1069','parentid' => '1038','name' => 'Бугуруслан'),
            array('id' => '1070','parentid' => '1038','name' => 'Гай'),
            array('id' => '1071','parentid' => '1038','name' => 'Сорочинск'),
            array('id' => '1072','parentid' => '1038','name' => 'Кувандык'),
            array('id' => '1073','parentid' => '1038','name' => 'Соль-Илецк'),
            array('id' => '1074','parentid' => '1038','name' => 'Медногорск'),
            array('id' => '1075','parentid' => '1038','name' => 'Саракташ'),
            array('id' => '1076','parentid' => '1038','name' => 'Абдулино'),
            array('id' => '1077','parentid' => '1038','name' => 'Ясный'),
            array('id' => '1078','parentid' => '1038','name' => 'Новосергиевка'),
            array('id' => '1079','parentid' => '1038','name' => 'Тоцкое Второе'),
            array('id' => '1080','parentid' => '1038','name' => 'Ивановка'),
            array('id' => '1081','parentid' => '1038','name' => 'Новоорск'),
            array('id' => '1082','parentid' => '1038','name' => 'Акбулак'),
            array('id' => '1083','parentid' => '1038','name' => 'Нежинка'),
            array('id' => '1084','parentid' => '1038','name' => 'Илек'),
            array('id' => '1085','parentid' => '32','name' => 'Москва'),
            array('id' => '1086','parentid' => '6','name' => 'Кировская область'),
            array('id' => '1087','parentid' => '1086','name' => 'Киров'),
            array('id' => '1088','parentid' => '1086','name' => 'Кирово-Чепецк'),
            array('id' => '1089','parentid' => '1086','name' => 'Вятские Поляны'),
            array('id' => '1090','parentid' => '1086','name' => 'Слободской'),
            array('id' => '1091','parentid' => '1086','name' => 'Котельнич'),
            array('id' => '1092','parentid' => '1086','name' => 'Омутнинск'),
            array('id' => '1093','parentid' => '1086','name' => 'Советск'),
            array('id' => '1094','parentid' => '1086','name' => 'Яранск'),
            array('id' => '1095','parentid' => '1086','name' => 'Зуевка'),
            array('id' => '1096','parentid' => '1086','name' => 'Белая Холуница'),
            array('id' => '1097','parentid' => '1086','name' => 'Луза'),
            array('id' => '1098','parentid' => '1086','name' => 'Вахруши'),
            array('id' => '1099','parentid' => '1086','name' => 'Кирс'),
            array('id' => '1100','parentid' => '1086','name' => 'Уржум'),
            array('id' => '1101','parentid' => '1086','name' => 'Сосновка'),
            array('id' => '1102','parentid' => '1086','name' => 'Нолинск'),
            array('id' => '1103','parentid' => '1086','name' => 'Оричи'),
            array('id' => '1104','parentid' => '1086','name' => 'Малмыж'),
            array('id' => '1105','parentid' => '1086','name' => 'Мурыгино'),
            array('id' => '1106','parentid' => '1086','name' => 'Даровской'),
            array('id' => '1107','parentid' => '18','name' => 'Себеж'),
            array('id' => '1108','parentid' => '11','name' => 'Ухта'),
            array('id' => '1109','parentid' => '14','name' => 'Черняховск'),
            array('id' => '1110','parentid' => '34','name' => 'Орел'),
            array('id' => '1111','parentid' => '20','name' => 'Нарьян-Мар'),
            array('id' => '1112','parentid' => '10','name' => 'пос.им. Свердлова'),
            array('id' => '1113','parentid' => '10','name' => 'Новое Девяткино'),
            array('id' => '1114','parentid' => '48','name' => 'пгт. Зеленовка')
        );

        DB::table('federal_dists')->insert($federalDist);
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('federal_dists');
    }
};
